---
title: "Diputados"
author: "Bernardino Araya"
date: "2025-11-06"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(writexl)
library(readxl)
```

```{r}
bd_dip_excel <- read_excel("Bases de datos/2021_11_Diputados_Datos_Eleccion.xlsx", skip = 4)
```

```{r}
colnames(bd_dip_excel)
```

```{r}
colnames(bd_dip_excel) <- c("nro_region", 
                            "region", 
                            "circ_sen", 
                            "distrito", 
                            "comuna", 
                            "lista", 
                            "pacto", 
                            "partido", 
                            "nro_voto", 
                            "nombres", 
                            "primer_apellido", 
                            "segundo_apellido", 
                            "votos", 
                            "cargo"
                            )
```

```{r}
bd_dip_excel <- bd_dip_excel |> select(region, 
                                       circ_sen, 
                                       distrito, 
                                       lista, 
                                       pacto, 
                                       partido, 
                                       nro_voto,
                                       nombres, 
                                       primer_apellido, 
                                       segundo_apellido, 
                                       votos, 
                                       cargo
                                       ) |>
 mutate(candidato = paste(nombres, primer_apellido, segundo_apellido))
```

```{r}
bd_dip_excel <- bd_dip_excel |>  group_by(region, 
                                          lista, 
                                          partido, 
                                          nro_voto, 
                                          candidato, 
                                          cargo, 
                                          pacto, 
                                          circ_sen, 
                                          distrito
                                          ) |>
  summarise(total_region = sum(votos, na.rm = TRUE)) |> 
  filter(!is.na(partido))
```

```{r}
diputados <- bd_dip_excel |> select(region, 
                                    circ_sen, 
                                    distrito, 
                                    lista, 
                                    nro_voto, 
                                    pacto, 
                                    partido, 
                                    candidato, 
                                    total_region, 
                                    cargo
                                    )
```

Guardar base de dato:

```{r}
write_rds(diputados, "output/base_diputados.rds")
```

