---
title: "Diputados"
author: "Bernardino Araya"
date: "2025-11-06"
output: html_document
---

```{r}
library(tidyverse)
library(writexl)
library(readxl)
library(dplyr)
```

```{r}
bd_dip_excel <- read_excel("C:/Users/berna/OneDrive/Escritorio/R_proyectos/Ramo MADD/1TrabajoGrupalR/GrupalICP5006/2021_11_Diputados_Datos_Eleccion.xlsx", skip = 4)
```

```{r}
colnames(bd_dip_excel)
```

```{r}
colnames(bd_dip_excel) <- c("nro_region", "region", "circ_sen", 
                            "distrito", "comuna", "lista", "pacto", 
                            "partido", "nro_voto", "nombres", 
                            "primer_apellido", "segundo_apellido", 
                            "votos", "cargo")
```

```{r}
bd_dip_excel <- bd_dip_excel |> select(region, circ_sen, 
                        distrito, lista, pacto, 
                        partido, nro_voto, nombres, 
                            primer_apellido, segundo_apellido, votos, cargo) |>
 mutate(candidato = paste(primer_apellido, segundo_apellido, ",", nombres))
```

```{r}
bd_dip_excel <- bd_dip_excel |>  group_by(region, lista, partido, 
                                          candidato, cargo, pacto, 
                                          circ_sen, distrito) |>
  summarise(total_region = sum(votos, na.rm = TRUE))
```

```{r}
diputados <- bd_dip_excel |> select(region, circ_sen, distrito, 
                                      lista, pacto, partido, 
                                      candidato, total_region, cargo)
```
